
s , t = input().split(' ')
s , t = int(s),int(t)
a , b = input().split(' ')
a , b = int(a),int(b)
m , n = input().split(' ')
m , n = int(m), int(n)
apple = list(map(int,input().split()))
orange = list(map(int,input().split()))
print(sum([1 for x in apple if (x + a) >= s and (x + a) <= t]))
print(sum([1 for x in orange if (x + b) >= s and (x + b) <= t]))
