
# txt = input()
# Alpha_num = txt.isalnum()
# Alpha_bet = txt.isalpha()
# Digit     = txt.isdigit()
# Lower     = txt.islower()
# Upper     = txt.isupper()
#
# print(Alpha_num)
# print(Alpha_bet)
# print(Digit)
# print(Lower)
# print(Upper)
str = input()
print (any(c.isalnum()  for c in str))
print (any(c.isalpha() for c in str))
print (any(c.isdigit() for c in str))
print (any(c.islower() for c in str))
print (any(c.isupper() for c in str))